package main 
 
import (          "strings" 
 )

func SortNumbers(numbers string) string{
    numbers = strings.Replace(numbers, " ", "", -1)
    numbers = strings.Replace(numbers, "zero", "0", -1)
    numbers = strings.Replace(numbers, "one", "1", -1)
    numbers = strings.Replace(numbers, "two", "2", -1)
    numbers = strings.Replace(numbers, "three", "3", -1)
    numbers = strings.Replace(numbers, "four", "4", -1)
    numbers = strings.Replace(numbers, "five", "5", -1)
    numbers = strings.Replace(numbers, "six", "6", -1)
    numbers = strings.Replace(numbers, "seven", "7", -1)
    numbers = strings.Replace(numbers, "eight", "8", -1)
    numbers = strings.Replace(numbers, "nine", "9", -1)
    numbers = strings.Replace(numbers, "ten", "10", -1)
    numbers = strings.Replace(numbers, "eleven", "11", -1)
    numbers = strings.Replace(numbers, "twelve", "12", -1)
    numbers = strings.Replace(numbers, "thirteen", "13", -1)
    numbers = strings.Replace(numbers, "fourteen", "14", -1)
    numbers = strings.Replace(numbers, "fifteen", "15", -1)
    numbers = strings.Replace(numbers, "sixteen", "16", -1)
    numbers = strings.Replace(numbers, "seventeen", "17", -1)
    numbers = strings.Replace(numbers, "eighteen", "18", -1)
    numbers = strings.Replace(numbers, "nineteen", "19", -1)
    numbers = strings.Replace(numbers, "twenty", "20", -1)
    numbers = strings.Replace(numbers, "thirty", "30", -1)
    numbers = strings.Replace(numbers, "forty", "40", -1)
    numbers = strings.Replace(numbers, "fifty", "50", -1)
    numbers = strings.Replace(numbers, "sixty", "60", -1)
    numbers = strings.Replace(numbers, "seventy", "70", -1)
    numbers = strings.Replace(numbers, "eighty", "80", -1)
    numbers = strings.Replace(numbers, "ninety", "90", -1)
    numbers = strings.Replace(numbers, "hundred", "00", -1)
    numbers = strings.Replace(numbers, "thousand", "000", -1)
    numbers = strings.Replace(numbers, "million", "000000", -1)
    numbers = strings.Replace(numbers, "billion", "000000000", -1)
    numbers = strings.Replace(numbers, "trillion", "000000000000", -1)
    numbers = strings.Replace(numbers, "quadrillion", "000000000000000", -1)
    numbers = strings.Replace(numbers, "quintillion", "00000000000